### ISSUE TITLE
[Sketchpacks Relay] Multiple manifest.json files prevent plugin from being indexed

### ISSUE THREAD

**Issue by adamkirkwood** [tarunmangukiya/sketch-logos#1]
Hey @tarunmangukiya,

We've found one more issue that is preventing your plugin from being indexed in our registry.

It seems that you have more than one `manifest.json` within your repo. Sketchpacks API doesn't know which one to parse.

We recommend placing the `manifest.json` that you want Sketchpacks to index closest to the root of your source code. Similar to `package.json`.

Once you've made those changes, please [uninstall then reinstall](https://github.com/Iconscout/logodrop/settings/installations) Sketchpacks Relay on this repository. (We're working on a dashboard to help with this uninstall/reinstall process)

Let us know if there is anything else we can help clarify.

**Comment by tarunmangukiya** [comment]
@adamkirkwood Thanks for mentioning. I have removed multiple `manifest.json` files, and kept only one that's related to the plugin.

Let me reinstall the Sketchpacks Relay.

Thanks 👍

**Comment by tarunmangukiya** [comment]
Hello Adam,

I have resolved the issue and re-installed the plugin yesterday. But still the Sketchpacks Relay has to picked up the plugin.

Can you look into the same?

Best,
Tarun
