### ISSUE TITLE
Plugin not working on 10.11

### ISSUE THREAD

**Issue by bomberstudios** [tarunmangukiya/sketch-logos#2]
Launching the plugin on 10.11 shows this:

![screen shot 2017-07-11 at 13 34 54](https://user-images.githubusercontent.com/3832/28069467-e2a80108-6649-11e7-9692-d53ca6a1cd51.png)

**Comment by tarunmangukiya** [comment]
Have you tried to update Sketch?
Can you give us the details about your Sketch version and OS version?

It'll help us to replicate the issue.

**Comment by bomberstudios** [comment]
We've tried this on the latest version of Sketch 45, running on macOS 10.11 (latest version)

**Comment by ddresch** [comment]
Not working macOS 10.11 Sketch 45.2 same screen like above.

Installed via Runner.

**Comment by dalpattapaniya** [comment]
Have you installed latest update of mac os?

**Comment by tarunmangukiya** [comment]
@bomberstudios @ddresch Hello there,

I have enabled logging for debugging purpose as I am unable to reproduce the issue. 

Can you try to install this version of plugin https://github.com/Iconscout/logodrop/archive/debugging-issue-%232.zip and open and close plugin for 3-5 times. This will help me collect logs.

**Comment by rghadamian** [comment]
also having this problem - it's saying that it can't find any logos?

**Comment by dalpattapaniya** [comment]
@RGhadamian Yes, there is some API Issue we're currently facing. You can download our icondrop plugin here : https://github.com/Iconscout/icondrop 

You'll able to search logo as well as icon with this plugin.

**Comment by eduardoduccigne** [comment]
Plugin not working on macOS Sierra 10.12.6 and Sketch 46.2. Nothing happens.

**Comment by tarunmangukiya** [comment]
We are working on it. Will release the bug fix in next week.

Does the screen comes blank?

**Comment by eduardoduccigne** [comment]
Nope. The screen never shows up. I click on "Logodrop" option in Plugins menu and nothing happens.

**Comment by tarunmangukiya** [comment]
Hi @eduardoduccigne 

Thanks for using our plugin. We suggest you to use Icondrop which is our Official plugin for icons, logos, and many more.

Let me know if you find any issue using it :)
