### ISSUE TITLE
Cannot search for any logos

### ISSUE THREAD

**Issue by julstrinh** [tarunmangukiya/sketch-logos#3]
I tried to search for logos and I always get this screen. 
<img width="434" alt="Screenshot 2019-05-10 at 12 51 30" src="https://user-images.githubusercontent.com/40603679/57525337-5a257f80-7322-11e9-97d3-5b41978cfbca.png">

**Comment by tarunmangukiya** [comment]
Hi @julstrinh ,

Thanks for using our plugin. We suggest you to use [Icondrop](https://iconscout.com/icondrop/) which is our Official plugin for icons, logos, and many more.

Let me know if you find any issue using it :)
